#include "emitter.h"
#include <string.h>

void emit_header(FILE* out) {
    fprintf(out,
        "// auto-generated by DolRecomp — do not edit\n"
        "\n"
        "#include \"runtime/runtime.h\"\n"
        "\n"
    );
}

void emit_footer(FILE* out) {
    fprintf(out, "\n// end of recompiled output\n");
}

void emit_instruction(FILE* out, const PPCInst* inst) {
    char disasm[64];
    ppc_disasm(disasm, sizeof(disasm), inst);
    fprintf(out, "    // %08X: %s\n", inst->address, disasm);

    switch (inst->op) {
    case PPC_OP_ADDI: // rA=0 means base is literal 0
        if (inst->rA == 0) {
            fprintf(out, "    ctx->gpr[%u] = (u32)(s32)(%d);\n",
                    inst->rD, (int)inst->simm);
        } else {
            fprintf(out, "    ctx->gpr[%u] = ctx->gpr[%u] + (u32)(s32)(%d);\n",
                    inst->rD, inst->rA, (int)inst->simm);
        }
        break;
    
    case PPC_OP_ADDIC: {
        fprintf(out, "    {\n");
        fprintf(out, "        u64 res = (u64)ctx->gpr[%u] + (u64)(s32)(%d);\n", 
                inst->rA, (int)inst->simm);
        fprintf(out, "        ctx->gpr[%u] = (u32)res;\n", inst->rD);
        fprintf(out, "        // Update XER[CA] (bit 2 / mask 0x20000000)\n");
        fprintf(out, "        u32 carry = (u32)((res >> 32) & 1);\n");
        fprintf(out, "        ctx->xer = (ctx->xer & ~0x20000000u) | (carry << 29);\n");
        fprintf(out, "    }\n");
        break;
    }

    case PPC_OP_ADDIS: // rA=0 means base is literal 0, shift immediate by 16
        if (inst->rA == 0) {
            fprintf(out, "    ctx->gpr[%u] = (u32)(inst->simm) << 16;\n",
                    inst->rD);
        } else {
            fprintf(out, "    ctx->gpr[%u] = ctx->gpr[%u] + ((u32)(inst->simm) << 16);\n",
                    inst->rD, inst->rA);
        }
        break;

    case PPC_OP_ORI:
        if (inst->rS == 0 && inst->rA == 0 && inst->uimm == 0) {
            fprintf(out, "    // nop\n");
        } else {
            fprintf(out, "    ctx->gpr[%u] = ctx->gpr[%u] | 0x%04Xu;\n",
                    inst->rA, inst->rS, inst->uimm);
        }
        break;

    case PPC_OP_LWZ: // rA=0 means base is 0
        if (inst->rA == 0) {
            fprintf(out, "    ctx->gpr[%u] = mem_read32(ctx, (u32)(s32)(%d));\n",
                    inst->rD, (int)inst->simm);
        } else {
            fprintf(out, "    ctx->gpr[%u] = mem_read32(ctx, ctx->gpr[%u] + (u32)(s32)(%d));\n",
                    inst->rD, inst->rA, (int)inst->simm);
        }
        break;

    case PPC_OP_STW: // same rA=0 rule
        if (inst->rA == 0) {
            fprintf(out, "    mem_write32(ctx, (u32)(s32)(%d), ctx->gpr[%u]);\n",
                    (int)inst->simm, inst->rS);
        } else {
            fprintf(out, "    mem_write32(ctx, ctx->gpr[%u] + (u32)(s32)(%d), ctx->gpr[%u]);\n",
                    inst->rA, (int)inst->simm, inst->rS);
        }
        break;

    case PPC_OP_B: // bl = call, b = goto
        if (inst->lk) {
            fprintf(out, "    ctx->lr = 0x%08Xu;\n", inst->address + 4);
            fprintf(out, "    func_%08X(ctx);\n", inst->branch_target);
        } else {
            fprintf(out, "    goto label_%08X;\n", inst->branch_target);
        }
        break;

    default:
        fprintf(out, "    // TODO: unimplemented (raw: 0x%08X)\n", inst->raw);
        break;
    }

    fprintf(out, "\n");
}

void emit_function(FILE* out, const PPCInst* insts, u32 count, u32 func_addr) {
    u32 i;

    fprintf(out, "void func_%08X(CPUState* ctx) {\n", func_addr);

    for (i = 0; i < count; i++) {
        fprintf(out, "label_%08X:\n", insts[i].address);
        emit_instruction(out, &insts[i]);
    }

    fprintf(out, "}\n\n");
}
